import asyncio
import sys
sys.path.insert(0, '/app/legiongasper_framework_0813')

from legiongasper.core.captain import Captain
from legiongasper.core.factory import AgentFactory
from legiongasper.core.squad import Squad
from legiongasper.config.captain_roles import ResearchLead

async def research_squad_demo():
    
    print("=" * 60)
    print("⚡ LEGIONGASPER Research Squad Demo")
    print("=" * 60)
    print()
    
    factory = AgentFactory()
    
    print("[1] Spawning Research Captain...")
    captain = Captain(
        agent_id="quantum_research_lead",
        role=ResearchLead(),
        llm_config={"model_tier": "premium"}
    )
    print(f"    ✓ Captain spawned: {captain.agent_id}")
    print()
    
    research_topic = "Latest developments in quantum computing in 2024"
    print(f"[2] Research Task: {research_topic}")
    print()
    
    print("[3] Captain decomposing task into subtasks...")
    subtasks = captain.decompose_task(research_topic)
    
    print(f"    Subtasks identified:")
    for i, subtask in enumerate(subtasks, 1):
        print(f"      {i}. {subtask['description']}")
    print()
    
    print("[4] Forming research squad...")
    squad = captain.form_squad(subtasks, factory)
    print(f"    ✓ Squad formed with {len(squad.agents)} agents")
    print(f"    Squad ID: {squad.squad_id}")
    print()
    
    print("[5] Squad Composition:")
    for agent in squad.agents:
        print(f"    - {agent.agent_id} ({agent.template_id})")
    print()
    
    print("[6] Executing parallel research...")
    print("    (Simulating research execution)")
    
    mock_results = [
        {
            "agent_id": squad.agents[0].agent_id if squad.agents else "agent_1",
            "subtask": subtasks[0] if subtasks else {"description": "Research"},
            "findings": [
                "IBM announced 1000+ qubit processor",
                "Google achieved quantum supremacy milestone",
                "New error correction protocols developed"
            ],
            "confidence": 0.92
        },
        {
            "agent_id": squad.agents[1].agent_id if len(squad.agents) > 1 else "agent_2",
            "subtask": subtasks[1] if len(subtasks) > 1 else {"description": "Analysis"},
            "findings": [
                "Quantum advantage demonstrated in chemistry simulation",
                "Commercial quantum cloud services expanded",
                "New quantum algorithms for optimization"
            ],
            "confidence": 0.88
        },
        {
            "agent_id": squad.agents[2].agent_id if len(squad.agents) > 2 else "agent_3",
            "subtask": subtasks[2] if len(subtasks) > 2 else {"description": "Synthesis"},
            "findings": [
                "Investment in quantum computing reached $1.4B",
                "Breakthrough in quantum networking",
                "Standardization efforts underway"
            ],
            "confidence": 0.85
        }
    ]
    
    await asyncio.sleep(1)
    print("    ✓ Research completed")
    print()
    
    print("[7] Captain aggregating results...")
    final_report = captain.aggregate_results(mock_results)
    
    print("    Aggregation method: weighted_confidence")
    print(f"    Sources: {len(mock_results)} agents")
    print(f"    Average confidence: {sum(r['confidence'] for r in mock_results) / len(mock_results):.2%}")
    print()
    
    print("=" * 60)
    print("📊 RESEARCH REPORT")
    print("=" * 60)
    print(f"Topic: {research_topic}")
    print(f"Generated by: {captain.agent_id}")
    print(f"Squad Size: {len(squad.agents)} agents")
    print("-" * 60)
    print()
    
    if final_report:
        print("Key Findings:")
        for i, finding in enumerate(final_report.get('key_findings', []), 1):
            print(f"  {i}. {finding}")
        print()
        
        print("Summary:")
        print(f"  {final_report.get('summary', 'No summary available')}")
        print()
        
        print("Recommendations:")
        for rec in final_report.get('recommendations', []):
            print(f"  • {rec}")
    else:
        print("Mock Report:")
        print("  Quantum computing has seen significant advances in 2024.")
        print("  Key areas include hardware improvements, algorithm development,")
        print("  and commercial applications. Error correction remains a")
        print("  critical focus area for achieving practical quantum advantage.")
    
    print()
    print("=" * 60)
    print("✓ Research Squad Demo Complete")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(research_squad_demo())